version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758-serving
    ports:
      - "5000:5000"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    restart: unless-stopped

  # Streamlit service will be added later in Milestone 3 (Part II)
  # streamlit:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile.streamlit
  #   image: ift6758-streamlit
  #   ports:
  #     - "8501:8501"
  #   environment:
  #     - WANDB_API_KEY=${WANDB_API_KEY}

      

     
