version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758-serving
    ports:
      - "5000:5000"
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
    restart: unless-stopped

  streamlit:
      build:
        context: .
        dockerfile: Dockerfile.streamlit
      image: ift6758-streamlit
      ports:
        - "8501:8501"
      environment:
        - WANDB_API_KEY=${WANDB_API_KEY}
        - SERVING_HOST=serving
        - SERVING_PORT=5000
      depends_on:
        - serving
      restart: unless-stopped

      

     
